version: '3.9'

networks:
  networkService:
    driver: bridge
    name: Inception-net
services:
  nginx:
    build: ./requirements/nginx/
    image: nginx:abait-ta
    container_name: nginx
    ports:
      - '443:443'
    environment:
      - .env
    depends_on:
      - wordpress
    networks:
      - networkService
    volumes:
      - FirstVM:/var/www/wordpress
  mariadb:
    build:
      context: ./requirements/mariadb
      args:
        DATA_BASENM: ${DATA_BASENM}
        NEWUSERNAME: ${NEWUSERNAME}
        USER_PASSWORD: ${USER_PASSWORD}
        NEWROOT_PASSWORD: ${NEWROOT_PASSWORD}
    image: mariadb:abait-ta
    container_name: mariadb
    expose:
      - "3306"
    networks:
      - networkService
    env_file:
      - .env
    volumes:
     - SecondVM:/var/lib/mysql
  wordpress:
    build:
      context: ./requirements/wordpress
    depends_on:
      - mariadb
      - redis
    image: wordpress:abait-ta
    container_name: wordpress
    networks:
      - networkService
    env_file:
      - .env
    expose:
      - "9000"
    volumes:
      - FirstVM:/var/www/wordpress
  redis:
    build:
     context: ./requirements/bonus/redis-service/
    image: redis:abait-ta
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - networkService
volumes:
  FirstVM:
    name : nginx-wordpress-VM
  SecondVM:
    name: mariadbVM