version: '3.9'

networks:
  networkService:
    driver: bridge
    name: Inception-net
services:
  nginx:
    build: ./requirements/nginx/
    image: nginx:abait-ta
    container_name: nginx
    ports:
      - '443:443'
    environment:
      - .env
    depends_on:
      - wordpress
    networks:
      - networkService
    volumes:
      - FirstVM:/var/www/wordpress
  mariadb:
    build:
      context: ./requirements/mariadb
      args:
        DATA_BASENM: ${DATA_BASENM}
        NEWUSERNAME: ${NEWUSERNAME}
        USER_PASSWORD: ${USER_PASSWORD}
        NEWROOT_PASSWORD: ${NEWROOT_PASSWORD}
    image: mariadb:abait-ta
    container_name: mariadb
    networks:
      - networkService
    environment:
      - .env
  wordpress:
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    image: wordpress:abait-ta
    container_name: wordpress
    networks:
      - networkService
    environment:
      - .env
    volumes:
      - FirstVM:/var/www/wordpress
volumes:
  FirstVM:
    name : nginx-wordpress-VM
    driver: local
    driver_opts:
      type : 'none'
      o : 'bind'
      device : /Users/abait-ta/Desktop/Inception/srcs/storeVMS


