version: '3.9'

networks:
  networkService:
    driver: bridge
    name: Inception-net
services:
  nginx:
    build: ./requirements/nginx/
    image: nginx:abait-ta
    container_name: nginx
    ports:
      - '443:443'
    environment:
      - .env
    depends_on:
      - wordpress
    networks:
      - networkService
    volumes:
      - FirstVM:/var/www/wordpress
    restart: always
  mariadb:
    build:
      context: ./requirements/mariadb
      args:
        DATA_BASENM: ${DATA_BASENM}
        NEWUSERNAME: ${NEWUSERNAME}
        USER_PASSWORD: ${USER_PASSWORD}
        NEWROOT_PASSWORD: ${NEWROOT_PASSWORD}
    image: mariadb:abait-ta
    container_name: mariadb
    expose:
      - "3306"
    networks:
      - networkService
    env_file:
      - .env
    volumes:
     - SecondVM:/var/lib/mysql
    restart: always
  wordpress:
    build:
      context: ./requirements/wordpress
    depends_on:
      - mariadb
      - redis
    image: wordpress:abait-ta
    container_name: wordpress
    networks:
      - networkService
    env_file:
      - .env
    expose:
      - "9000"
    volumes:
      - FirstVM:/var/www/wordpress
    restart: always
  redis:
    build:
     context: ./requirements/bonus/redis-service/
    image: redis:abait-ta
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - networkService
    restart: always
  website:
    build:
     context: ./requirements/bonus/static-website/
    image: mywebsite:abait-ta
    container_name: mywebsite
    ports:
     - '2222:80'
    restart: on-failure
  portainer:
   build:
    context: ./requirements/bonus/portainer-service/
   image: portainer:abait-ta
   container_name: portainer
   ports:
    - '9443:9443'
   volumes:
    - third-volume:/data
    - /var/run/docker.sock:/var/run/docker.sock
   restart: on-failure
volumes:
  FirstVM:
    name : nginx-wordpress-VM
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/abait-ta/data/wordpress

  SecondVM:
    name: mariadbVM
    driver: local 
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/abait-ta/data/mariadb

  third-volume:
    name: portainer_data
    driver: local 
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/abait-ta/data/portainer